version: '3.8'

services:
  android:
    build: .
    volumes:
      - .:/workspace
    ports:
      - "8080:8080"
    environment:
      - ANDROID_HOME=/usr/local/android-sdk
      - PATH=/usr/local/android-sdk/cmdline-tools/bin:$PATH
